/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  price?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  active?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  status: "active" | "hidden";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  status: "active" | "hidden";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  shortName: string;
  description: string;
  url: string;
  locale: string;
  contact?: {
    email: string;
    phone: string;
  };
  navigation?: Array<{
    label: string;
    href: string;
    _key: string;
  }>;
  social?: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | CaseStudy
  | Service
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {    name,    shortName,    description,    url,    locale,    contact { email, phone },    navigation[] { _key, label, href },    social { facebook, instagram, linkedin }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      name: string;
      shortName: null;
      description: string;
      url: null;
      locale: null;
      contact: null;
      navigation: null;
      social: null;
    }
  | {
      name: string;
      shortName: null;
      description: string;
      url: string | null;
      locale: null;
      contact: null;
      navigation: null;
      social: null;
    }
  | {
      name: null;
      shortName: null;
      description: string | null;
      url: string;
      locale: null;
      contact: null;
      navigation: null;
      social: null;
    }
  | {
      name: string;
      shortName: null;
      description: string | null;
      url: null;
      locale: null;
      contact: null;
      navigation: null;
      social: null;
    }
  | {
      name: string;
      shortName: string;
      description: string;
      url: string;
      locale: string;
      contact: {
        email: string;
        phone: string;
      } | null;
      navigation: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
      social: {
        facebook: string | null;
        instagram: string | null;
        linkedin: string | null;
      } | null;
    }
  | null;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service" && status == "active"] | order(name asc) {    _id,    name,    slug,    description,    image  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  description: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: SERVICE_QUERY
// Query: *[    _type == "service" &&    slug.current == $slug &&    status == "active"  ][0] {    _id,    name,    slug,    description,    image  }
export type SERVICE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  description: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: SERVICES_SITEMAP_QUERY
// Query: *[    _type == "service" &&    status == "active" &&    defined(slug.current) &&    slug.current != ""  ] | order(slug.current asc) {    "slug": slug.current,    _updatedAt  }
export type SERVICES_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: REFERENCES_QUERY
// Query: *[_type == "caseStudy" && status == "active"] | order(name asc) {    _id,    name,    slug,    description,    image,    url  }
export type REFERENCES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  description: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
}>;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: REFERENCE_QUERY
// Query: *[    _type == "caseStudy" &&    slug.current == $slug &&    status == "active"  ][0] {    _id,    name,    slug,    description,    image,    url  }
export type REFERENCE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  description: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
} | null;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: REFERENCES_SITEMAP_QUERY
// Query: *[    _type == "caseStudy" &&    status == "active" &&    defined(slug.current) &&    slug.current != ""  ] | order(slug.current asc) {    "slug": slug.current,    _updatedAt  }
export type REFERENCES_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: PRODUCTS_SITEMAP_QUERY
// Query: *[    _type == "product" &&    active == true &&    defined(slug.current) &&    slug.current != ""  ] | order(slug.current asc) {    "slug": slug.current,    _updatedAt  }
export type PRODUCTS_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[    _type == "product" &&    active == true  ] | order(name asc) {    _id,    name,    slug,    description,    price,    image,    featured  }
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  description: string | null;
  price: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  featured: boolean | null;
}>;

// Source: ../mhwd-next-starter/src/sanity/lib/queries.ts
// Variable: PRODUCT_QUERY
// Query: *[    _type == "product" &&    slug.current == $slug &&    active == true  ][0] {    _id,    name,    slug,    description,    price,    image,    featured  }
export type PRODUCT_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  description: string | null;
  price: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  featured: boolean | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0] {\n    name,\n    shortName,\n    description,\n    url,\n    locale,\n    contact { email, phone },\n    navigation[] { _key, label, href },\n    social { facebook, instagram, linkedin }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "service" && status == "active"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description,\n    image\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[\n    _type == "service" &&\n    slug.current == $slug &&\n    status == "active"\n  ][0] {\n    _id,\n    name,\n    slug,\n    description,\n    image\n  }\n': SERVICE_QUERY_RESULT;
    '\n  *[\n    _type == "service" &&\n    status == "active" &&\n    defined(slug.current) &&\n    slug.current != ""\n  ] | order(slug.current asc) {\n    "slug": slug.current,\n    _updatedAt\n  }\n': SERVICES_SITEMAP_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && status == "active"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description,\n    image,\n    url\n  }\n': REFERENCES_QUERY_RESULT;
    '\n  *[\n    _type == "caseStudy" &&\n    slug.current == $slug &&\n    status == "active"\n  ][0] {\n    _id,\n    name,\n    slug,\n    description,\n    image,\n    url\n  }\n': REFERENCE_QUERY_RESULT;
    '\n  *[\n    _type == "caseStudy" &&\n    status == "active" &&\n    defined(slug.current) &&\n    slug.current != ""\n  ] | order(slug.current asc) {\n    "slug": slug.current,\n    _updatedAt\n  }\n': REFERENCES_SITEMAP_QUERY_RESULT;
    '\n  *[\n    _type == "product" &&\n    active == true &&\n    defined(slug.current) &&\n    slug.current != ""\n  ] | order(slug.current asc) {\n    "slug": slug.current,\n    _updatedAt\n  }\n': PRODUCTS_SITEMAP_QUERY_RESULT;
    '\n  *[\n    _type == "product" &&\n    active == true\n  ] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description,\n    price,\n    image,\n    featured\n  }\n': PRODUCTS_QUERY_RESULT;
    '\n  *[\n    _type == "product" &&\n    slug.current == $slug &&\n    active == true\n  ][0] {\n    _id,\n    name,\n    slug,\n    description,\n    price,\n    image,\n    featured\n  }\n': PRODUCT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
